/**********************************************************************************
 * File Name : xmc_crc_sw_conf.c
 *
 * Description: This file has CRC s/w configuration for XMC1xxx MCUs.
 *
 * Related Document: See README.md
 *
 **********************************************************************************
 *
 * Copyright (c) 2015-2021, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are
 * permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the  following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * Neither the name of the copyright holders nor the names of its contributors may be
 * used to endorse or promote products derived from this software without specific prior
 * written permission.
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Change History
 * --------------
 *
 * 2015-02-16:
 *     - Initial version<br>
 *
 * 2015-04-06:
 *     - comments added <br>
 *
 * 2017-11-30:
 *     - Fix inversion
 *
 *****************************************************************************/

/*****************************************************************************
 * HEADER FILES
 ****************************************************************************/
#include "xmc_crc_sw.h"

/****************************************************************************
 * DATA STRUCTURES
 ***************************************************************************/

/* Look up table for the crc-width ranging from 1-bit to 8-bit CRC computation */
uint8_t crc_table_CRC_SW_0[256] =
{
0,
213,
127,
170,
254,
43,
129,
84,
41,
252,
86,
131,
215,
2,
168,
125,
82,
135,
45,
248,
172,
121,
211,
6,
123,
174,
4,
209,
133,
80,
250,
47,
164,
113,
219,
14,
90,
143,
37,
240,
141,
88,
242,
39,
115,
166,
12,
217,
246,
35,
137,
92,
8,
221,
119,
162,
223,
10,
160,
117,
33,
244,
94,
139,
157,
72,
226,
55,
99,
182,
28,
201,
180,
97,
203,
30,
74,
159,
53,
224,
207,
26,
176,
101,
49,
228,
78,
155,
230,
51,
153,
76,
24,
205,
103,
178,
57,
236,
70,
147,
199,
18,
184,
109,
16,
197,
111,
186,
238,
59,
145,
68,
107,
190,
20,
193,
149,
64,
234,
63,
66,
151,
61,
232,
188,
105,
195,
22,
239,
58,
144,
69,
17,
196,
110,
187,
198,
19,
185,
108,
56,
237,
71,
146,
189,
104,
194,
23,
67,
150,
60,
233,
148,
65,
235,
62,
106,
191,
21,
192,
75,
158,
52,
225,
181,
96,
202,
31,
98,
183,
29,
200,
156,
73,
227,
54,
25,
204,
102,
179,
231,
50,
152,
77,
48,
229,
79,
154,
206,
27,
177,
100,
114,
167,
13,
216,
140,
89,
243,
38,
91,
142,
36,
241,
165,
112,
218,
15,
32,
245,
95,
138,
222,
11,
161,
116,
9,
220,
118,
163,
247,
34,
136,
93,
214,
3,
169,
124,
40,
253,
87,
130,
255,
42,
128,
85,
1,
212,
126,
171,
132,
81,
251,
46,
122,
175,
5,
208,
173,
120,
210,
7,
83,
134,
44,
249,
};
CRC_SW_CONFIG_t CRC_SW_0_config =
{
  .crc_width = 8,
  .crc_poly = 213,
  .crc_initval = 0,
  .input_reflection =  false,
  .output_reflection = false,
  .output_inversion = 0x0U
};
CRC_SW_t CRC_SW_0 =
{
  .config = &CRC_SW_0_config,
  .crc_runningval = 0U,
  .msb_mask = 0U,
  .crc_mask = 0U,
  .crc_shift = 0U,
  .crctable = (uint32_t*)&crc_table_CRC_SW_0,
  .tableoffset = 1U
};
